AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EKS Cluster with Managed Node Group in Default VPC

Parameters:
  ClusterName:
    Type: String
    Default: MyEksCluster
  NodeGroupName:
    Type: String
    Default: MyNodeGroup
  NodeInstanceType:
    Type: String
    Default: t3.medium
  NodeCount:
    Type: Number
    Default: 2
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of subnet IDs in the default VPC
    Default: "subnet-058ce05b5dacbd3f5,subnet-0fe344e854b582365,subnet-078928768ceeda3a5"

Resources:

  # IAM Role for EKS Control Plane
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPublicAccess: true

  # IAM Role for EKS Nodes
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # Node Group
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: !Ref NodeGroupName
      ScalingConfig:
        MinSize: 1
        DesiredSize: !Ref NodeCount
        MaxSize: 3
      Subnets: !Ref SubnetIds
      NodeRole: !GetAtt NodeInstanceRole.Arn
      InstanceTypes:
        - !Ref NodeInstanceType
      AmiType: AL2_x86_64
      DiskSize: 20

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
  NodeGroupName:
    Value: !Ref NodeGroup
  ClusterRoleArn:
    Value: !GetAtt EKSClusterRole.Arn
  NodeInstanceRoleArn:
    Value: !GetAtt NodeInstanceRole.Arn
